# CELL TOWER COVERAGE

## Problem Description

A telecommunications company needs to build a set of mobile phone towers to provide signal coverage to the inhabitants of a given city. Several potential locations have been identified where the towers could be built. The towers have a fixed range and due to budget restrictions, only a limited number of them can be built. Given these restrictions, the company wants to provide coverage to the largest possible percentage of the population. To simplify the problem, the company has divided the area it wants to cover into a set of regions, each of which has a known population. The objective is then to choose in which of the potential locations the company should build cell phone towers, to provide coverage to as many people as possible. 

### RANDOM DATA GENERATION

In [2]:
import numpy as np

number_of_towers = 20
number_of_regions = 10

tower_coverage = np.random.randint(0, 2, size=(number_of_towers, number_of_regions))
population_region = np.random.randint(1, 100, size=(number_of_regions))
tower_cost = np.random.randint(1, 100, size=(number_of_towers))
budget = np.random.randint(1, 1000)

### TOWER COVERAGE BY REGION

In [3]:
print(tower_coverage)

[[0 1 1 1 1 1 1 1 1 0]
 [0 0 1 1 0 1 1 1 1 1]
 [1 0 1 0 0 1 1 1 0 1]
 [1 0 1 0 0 0 0 0 0 1]
 [0 1 0 1 0 1 0 1 0 0]
 [0 1 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0 1]
 [1 0 1 1 1 1 0 0 1 1]
 [0 0 1 1 0 1 0 0 0 0]
 [1 1 1 0 0 1 1 1 1 1]
 [0 0 0 1 0 1 1 1 1 0]
 [0 0 1 1 0 0 0 0 0 1]
 [0 0 0 1 0 0 1 1 0 0]
 [1 0 0 1 0 0 1 1 0 0]
 [0 1 0 1 0 0 0 0 0 1]
 [0 0 1 0 0 0 1 0 0 0]
 [1 0 1 1 0 0 0 0 0 1]
 [0 1 1 1 1 0 0 0 0 1]
 [1 0 0 1 0 0 0 0 0 1]
 [1 0 0 0 1 0 0 0 1 0]]


### POPULATION BY REGION

In [4]:
print(population_region)

[27 18 16 82 38 54 44 69 62 93]


### TOWER COST

In [5]:
print(tower_cost)

[26 45 51 88 35 66 50 11 86 11 75 81 71 12 88 38 73  4 33  1]


### BUDGET

In [6]:
print(budget)

423


# PEQNP TENSOR MODEL

In [7]:
import peqnp as cnf

cnf.engine(10)

X = cnf.tensor(dimensions=(number_of_towers, number_of_regions))

# ensure that at least one tower that covers a region must be selected.
for i in range(number_of_towers):
    assert sum(X[[i, j]](0, 1) for j in range(number_of_regions)) == 1

# ensure that at least one tower that covers a region must be selected.
for j in range(number_of_regions):
    assert sum(X[[i, j]](0, 1) for i in range(number_of_towers)) >= 1    

# ensure that the total cost of building towers do not exceed the allocated budget.
for i in range(number_of_towers):
    assert sum(X[[i, j]](0, tower_cost[i]) for j in range(number_of_regions)) <= budget

X_opt = None
optimal = 0
while True:
    
    # We seek to maximize the total population covered by the towers.
    assert sum(X[[i, j]](0, population_region[j] * tower_coverage[i, j]) for i in range(number_of_towers) for j in range(number_of_regions)) > optimal

    if cnf.satisfy(turbo=True):
        X_opt = np.vectorize(int)(X.binary)
        optimal = sum(X_opt[i][j] * population_region[j] * tower_coverage[i, j] for i in range(number_of_towers) for j in range(number_of_regions))        
        print(optimal)
    else:
        print(X_opt)
        break

if X_opt is None:
    print('Infeasible...')    

797
813
864
916
967
1008
1017
1023
[[0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]


#### Copyright © 2021 PEQNP